import http from 'node:http';
import { EventEmitter } from 'node:events';
import QRCode from 'qrcode';
const bus = new EventEmitter(), logs = [], messages = [], groups = new Map();
let ridePublisher;
const state = { connection: 'starting', qrImage: null, pairingCode: null };
const emit = (event, data) => bus.emit(event, data);
function addLog(level, message, data = {}) { const item = { level, message, data, time: new Date().toISOString() }; logs.push(item); if (logs.length > 60) logs.shift(); emit('log', item); }
export const dashboard = {
  setRidePublisher: (publisher) => { ridePublisher = publisher; },
  log: { info: (d,m) => addLog('info',m,d), warn: (d,m) => addLog('warn',m,d), error: (d,m) => addLog('error',m,d) },
  setConnection: v => { state.connection=v; emit('state',state); },
  setQr: async qr => { state.qrImage=qr?await QRCode.toDataURL(qr,{width:300,margin:2}):null; emit('state',state); },
  setPairingCode: v => { state.pairingCode=v; emit('state',state); },
  setTrackedGroups: jids => { jids.forEach(jid => groups.set(jid,groups.get(jid)||{jid,name:'Loading group…',inviteUrl:null})); emit('groups',[...groups.values()]); },
  updateGroup: group => { groups.set(group.jid,{...groups.get(group.jid),...group}); emit('groups',[...groups.values()]); },
  addGroupMessage: message => { messages.unshift(message); if(messages.length>150)messages.pop(); emit('message',message); },
};
const page = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ride Communications</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f7f4;color:#16261d;font:15px system-ui,sans-serif}.wrap{max-width:1080px;margin:auto;padding:32px 18px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}.eyebrow{color:#0c8241;font-size:11px;font-weight:800;letter-spacing:.13em;text-transform:uppercase;margin:0}h1{font-size:30px;margin:3px 0}h2{margin:0;font-size:19px}.status{background:#e4ebe6;border-radius:99px;padding:8px 12px;font-weight:700}.status.open{background:#d9f5e4;color:#087537}.grid{display:grid;grid-template-columns:310px 1fr;gap:20px}.card{background:#fff;border:1px solid #dce6df;border-radius:16px;padding:20px;box-shadow:0 6px 18px #14321a09}.icon{font-size:26px;background:#dff7e9;border-radius:13px;padding:10px;display:inline-block;margin-bottom:12px}.jid{display:block;font:12px monospace;color:#68766e;word-break:break-all;margin-top:7px}.button{display:block;margin-top:18px;text-align:center;text-decoration:none;background:#108946;color:#fff;border-radius:9px;padding:11px;font-weight:750}.disabled{background:#dfe7e2;color:#6a756e;pointer-events:none}.note{color:#68766e;font-size:13px}.feed-head{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid #e5ece7;padding-bottom:13px}.count{color:#68766e;font-size:13px}.message{padding:16px 0;border-bottom:1px solid #edf1ee}.sender{font-weight:800}.time{color:#68766e;font-size:12px;margin-left:8px}.text{white-space:pre-wrap;word-break:break-word;margin-top:6px;font-size:16px}.empty{color:#68766e;text-align:center;padding:50px 0}.link{margin-top:22px}.link img{max-width:280px;width:100%;display:none;margin-top:10px}.link p{color:#68766e;font-size:13px}.activity{margin-top:20px}.logs{max-height:200px;overflow:auto;background:#122019;color:#dcefe3;padding:12px;border-radius:9px;font:12px monospace;white-space:pre-wrap}@media(max-width:700px){.grid{grid-template-columns:1fr}.wrap{padding-top:20px}}</style></head><body><main class="wrap"><header class="top"><div><p class="eyebrow">WhatsApp bridge</p><h1>Ride communications</h1></div><span id="status" class="status">Connecting…</span></header><div class="grid"><aside class="card"><div class="icon">🚗</div><h2 id="name">Tracked group</h2><code id="jid" class="jid">Loading…</code><a id="open" class="button disabled" target="_blank" rel="noopener">Open WhatsApp group</a><p id="note" class="note">Loading group access…</p><div class="link"><h2>Link WhatsApp</h2><p id="help">Waiting for a QR code…</p><img id="qr"><p id="pair"></p></div></aside><section class="card"><header class="feed-head"><div><p class="eyebrow">Live feed</p><h2 id="feed">Tracked group</h2></div><span id="count" class="count">0 messages</span></header><div id="messages"><p class="empty">Waiting for messages from this group.</p></div></section></div><details class="card activity"><summary>Connection activity</summary><div id="logs" class="logs"></div></details></main><script>
const $=s=>document.querySelector(s),msgs=$('#messages'),logs=$('#logs');let count=0;function state(s){$('#status').textContent=s.connection==='open'?'WhatsApp connected':s.connection;$('#status').className='status '+s.connection;$('#qr').src=s.qrImage||'';$('#qr').style.display=s.qrImage?'block':'none';$('#help').textContent=s.qrImage?'Scan this QR in WhatsApp → Linked Devices.':s.connection==='open'?'This account is linked.':'Waiting for WhatsApp…';$('#pair').textContent=s.pairingCode?'Pairing code: '+s.pairingCode:''}function groups(g){let x=g[0];if(!x)return;$('#name').textContent=x.name;$('#feed').textContent=x.name;$('#jid').textContent=x.jid;let a=$('#open');if(x.inviteUrl){a.href=x.inviteUrl;a.classList.remove('disabled');$('#note').textContent='Opens this group in WhatsApp.'}else{$('#note').textContent='Group link is unavailable for this WhatsApp account.'}}function message(m){msgs.querySelector('.empty')?.remove();let e=document.createElement('article');e.className='message';let s=document.createElement('span');s.className='sender';s.textContent=m.senderName||m.senderJid||'Unknown sender';let t=document.createElement('span');t.className='time';t.textContent=new Date(m.timestamp*1000).toLocaleString();let b=document.createElement('div');b.className='text';b.textContent=m.text||'[Media message]';e.append(s,t,b);msgs.prepend(e);count++;$('#count').textContent=count+' message'+(count===1?'':'s')}let es=new EventSource('events');es.addEventListener('state',e=>state(JSON.parse(e.data)));es.addEventListener('groups',e=>groups(JSON.parse(e.data)));es.addEventListener('messages',e=>JSON.parse(e.data).reverse().forEach(message));es.addEventListener('message',e=>message(JSON.parse(e.data)));es.addEventListener('log',e=>{let x=JSON.parse(e.data);logs.textContent+='['+x.time+'] '+x.message+' '+JSON.stringify(x.data)+'\\n'});</script></body></html>`;
function sse(res,event,data){res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`)}
export function startDashboard({host,port}) { const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='POST'&&url.pathname==='/publish-ride'){try{let raw='';for await(const c of req)raw+=c;if(raw.length>10000)throw new Error('Request too large');const id=await ridePublisher(JSON.parse(raw));res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:true,messageId:id}))}catch(e){res.writeHead(422,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:e.message}))}return}if(req.method==='GET'&&url.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(page);return}if(req.method==='GET'&&url.pathname==='/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform',Connection:'keep-alive'});sse(res,'state',state);sse(res,'groups',[...groups.values()]);sse(res,'messages',messages);logs.forEach(x=>sse(res,'log',x));const h={state:x=>sse(res,'state',x),groups:x=>sse(res,'groups',x),message:x=>sse(res,'message',x),log:x=>sse(res,'log',x)};Object.entries(h).forEach(([e,f])=>bus.on(e,f));req.on('close',()=>Object.entries(h).forEach(([e,f])=>bus.off(e,f)));return}res.writeHead(404);res.end('Not found')});server.on('error',e=>dashboard.log.error({error:e.message},'Dashboard server failed'));server.listen(port,host,()=>dashboard.log.info({url:`http://${host}:${port}`},'Dashboard available'));return server }
